language: ruby
rvm:
- 2.3.1
script: bundle exec rspec
deploy:
  provider: heroku
  app: citibike-jsa
  api_key:
    secure: jG/g7dAFnkVW6YwjUAIO95LJLSaf8zWVgdVly52fjwb+p1YGp2G1/g0WeBmyCEzqvtd2bhdRbXySQilJpo1fIInfmARwYefLLQKm44mrfG+g2kA4Z9ATiFNVADNj2FAtbDK6IM9mJZnuzR6gZ1M2J4uouBcZ3w6x2dXLdeAInbC8fVSFJytmdxoplERxA4WeF3gYUbTGaNxZ4LAUAc9Zl2MtNuZlSttnNt6xtzglT9Bf/FCoVUb8HGjL8I90ddrMCjb/SVw7rV1OppWNW8omvW0a/JLkOgufNjuXBFyc1s7hcQc9T56WZ3yauNvCxvaDssziCvynmpIrMkEG46WFggYUvSErRkuGr6tXopmLjOfgU4o0x6FcLQkTWu4UK9w0dbac2l8LNFMaKCEXatYIQcw6Tv9OwXLs9M+NADWf4ONPa8KbM1+l811Ggyk3irmqELalHqtUrjpr1rh2SW+65DCAEOXDftEjByx+lWCxoPpUYyU8qnO/OUVNdE6+uYgDS+oS0/UsPANwXyt8dK7nVxknNwGEpUifPhKnCNP3NahD5zgXugZuS8W6FE5SmJgRwERbbzNEiuCFQT5mny+GJbnzLGPn68Ear/EjwsjOMYVkc/4dB5+QdPXcvV92YVpVj+WAsGu8CKzRy1sLc315iyJfS/TsH8qFzO27am9F6Fw=
